### ISSUE TITLE
Chubaofs comparison with Hadoop Ozone, OpenEBS

### ISSUE THREAD

**Issue by nrchakradhar** [chubaofs/chubaofs#368]
**Is your feature request related to a problem? Please describe.**
Is there any comparison available between Chubaofs compares with Hadoop Ozone?

**Describe the solution you'd like**
At a high level, Chubaofs, Hadoop Ozone and OpenEBS look similar. If there is some comparison of features, functionality, suitability for usecases is provided, it will be very useful. 
All projects seem to integrate with Rook and provide CSI option also.

I have seen the [page](https://chubaofs.readthedocs.io/en/latest/faq.html#ceph) but it does not compare with Hadoop Ozone, OpenEBS.

**Comment by awzhgw** [comment]
@nrchakradhar  thank you for your advice。
We will increase the comparison with hadoop ozone, especially in usecase, features, etc.
Can you help us do this work and become our contributors?

**Comment by nrchakradhar** [comment]
@awzhgw I do not think I have enough expertise to make a comparison. I am a newbie to ChubaoFS and have some experience in HDFS.
We wanted to evaluate newer storage choices in Cloud Native world and were considering to start with CephFS. Since HDFS was in use, we naturally thought of exploring Ozone. During this exploratory work, we found ChubaoFS in the CNCF projects. ChubaoFS is also interesting for us to explore. I would wait for an expert to make a proper technical comparison.

**Comment by bladehliu** [comment]
@nrchakradhar thanks your good question. we will improve our document and here I just give some simple descriptions. hope that helps. 

In short, ChubaoFS is a distributed file system and object store _in one system_. Since it supports POSIX-compatible filesystem interface, It can be _mounted_ by a containerized platform like Kubernetes or by non-containerized bare metal servers. And it provides S3-compatible API so can be used as a private object store service. ChubaoFS has its own highly scalable architecture of namespace/metadata and data management and adopts consistent replication protocols. 

Apache Hadoop Ozone is a distributed object store compatible with HDFS, so should be easily integrated into the existing Hadoop ecosystem. 

OpenEBS is built for Kubernetes, supporting various storage engines including ChubaoFS. 


Later let's add more in-depth technical and experimental comparisons to the docs.

**Comment by nrchakradhar** [comment]
@bladehliu Thanks for the information. Look forward more details.

**Comment by awzhgw** [comment]
@ZhuZhengyi  please add  comparison with hadoop ozone on https://chubaofs.readthedocs.io/en/latest/faq.html
