### ISSUE TITLE
multi-tenancy security

### ISSUE THREAD

**Issue by skybabydad** [chubaofs/chubaofs#383]
**Is your feature request related to a problem? Please describe.**
current volume setting only seperate different tenant by volume.
if a unexperienced admininstor name the volumes by some pattern, for example:
001,002....
or 
order/customer/account/
or 
blabla

then a malicious tenant will easily mount other tenant's volumn and steal other tenant's data.

it will be a huge secruity vulnerablity.

**Describe the solution you'd like**

volume setting should invlove some security mechnism such as appsecret to prevent hacker to guess.

**Describe alternatives you've considered**

as a workround, in maintaince manual, we can suggest administrators should use a passcode generator or something a like to generate a strong  volume name.

**Additional context**

{
  "mountPoint": "/mnt/fuse",
  "volName": "test",
  "owner": "cfs",
  "masterAddr": "192.168.31.173:80,192.168.31.141:80,192.168.30.200:80",
  "logDir": "/export/Logs/client",
  "warnLogDir":"/export/home/tomcat/UMP-Monitor/logs/",
  "profPort": "10094",
  "logLevel": "info"
}

**Comment by awzhgw** [comment]
@skybabydad  it is a good Suggest， 
We will support it in the next release

**Comment by mervinkid** [comment]
Hi @skybabydad ,
Thanks for your feedback.

Development of multi-tenant security is ongoing and is nearing completion.

ChubaoFS is a distributed fusion storage system. We also provide a POSIX-compatible file system interface and an Amazon S3-compatible object storage interface.

In order to provide more flexible security policies in the multi-tenant environment, we are developing highly granular user security authentication functions.

**Comment by mervinkid** [comment]
@skybabydad 

We have a solution based on user security and authorization to improve access control of multi-tenant resources. This solution is described in issue #423 .

Under this solution, users could have multiple volumes, and could authorize other users to read-only or writable permissions on some volumes of their own, or revoke authorization at any time.
