### ISSUE TITLE
haven't deregister master when stop && have't add health check consul  health check for master

### ISSUE THREAD

**Issue by wwq-2020** [chubaofs/chubaofs#405]
**Describe the bug**

**Environment**
Describe your server system version, kernel version

**To Reproduce**

**Expected behavior**

**Additional context**

	cInfo := &ConsulRegisterInfo{
		Name:    app,
		ID:      id,
		Address: host,
		Port:    port,
		Tags: []string{
			"app=" + app,
			"role=" + role,
			"cluster=" + cluster,
		},
	}

**Comment by mervinkid** [comment]
> **Describe the bug**
> A clear and concise description of what the bug is.
> 
> **Environment**
> Describe your server system version, kernel version
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> 
> **Additional context**
> Add any other context about the problem here.
> 
> ```
> cInfo := &ConsulRegisterInfo{
> 	Name:    app,
> 	ID:      id,
> 	Address: host,
> 	Port:    port,
> 	Tags: []string{
> 		"app=" + app,
> 		"role=" + role,
> 		"cluster=" + cluster,
> 	},
> }
> ```

Hi @wwq1988 ,
The description of this issue is very unclear.
Please describe in detail.

**Comment by mervinkid** [comment]
@wwq1988 

I now answer the information in your title.

1. Why do you think the component needs to be unregistered with the master when it is stopped. In actual use, there will be many artificial and temporary stops of nodes due to various reasons, such as server maintenance and restart. These nodes will be restarted and serviced shortly after maintenance. If a component is removed from the cluster after it is stopped, the system will rebuild the data copy on the stopped node on other online nodes in the cluster in order to ensure sufficient data copy redundancy. This will cause a lot of unnecessary performance loss.

2. consul is used to serve Prometheus. It is only a third-party and optional component. It is not a part of ChubaoFS. From the semantics of the entire project and components, he does not need the master to manage it. The master is our resource manager who is only responsible for managing the resources of the ChubaoFS cluster.

**Comment by wwq1988** [comment]
@mervinkid ok
