### ISSUE TITLE
no node set available for creating a meta partition

### ISSUE THREAD

**Issue by sxb12345** [chubaofs/chubaofs#505]
[root@localhost datanode]# curl -v "http://172.28.168.154:17010/metaNode/decommission?addr=172.28.168.154:17210"
* About to connect() to 172.28.168.154 port 17010 (#0)
*   Trying 172.28.168.154...
* Connected to 172.28.168.154 (172.28.168.154) port 17010 (#0)
> GET /metaNode/decommission?addr=172.28.168.154:17210 HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 172.28.168.154:17010
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Length: 100
< Content-Type: application/json
< Date: Fri, 17 Apr 2020 11:20:23 GMT
< 
* Connection #0 to host 172.28.168.154 left intact
{"code":1,"msg":"[cluster.go 1247] no node set available for creating a meta partition","data":null}[root@localhost datanode]#

**Comment by mervinkid** [comment]
Hi @sxb12345 .
Because ChubaoFS's metadata is all in memory, MetaNode reserves a portion of its memory to ensure normal service. If the amount of available memory minus the reserved memory of the MetaNode is less than 0, the MetaNode will switch itself to the read-only state.
When creating a volume, the default metadata is three copies. The master will ensure that there are more than three writable MetaNodes in the cluster to succeed, otherwise it will fail to create.

The MetaNode reserved memory configuration item is `totalMem`.

Reference:
[Meta Subsystem — ChubaoFS documentation] (https://chubaofs.readthedocs.io/en/latest/user-guide/metanode.html)
