### ISSUE TITLE
No clean umount when stopping the fuse client

### ISSUE THREAD

**Issue by netdata-be** [chubaofs/chubaofs#541]
**Describe the bug**
When stopping the fuse client (cfs-client) the mointpoint does not get umounted resulting in the following error:
```
ls -al mountpoint/
ls: cannot open directory 'mountpoint/': Transport endpoint is not connected
```

**Comment by awzhgw** [comment]
@netdata-be  how stop cfs-client ?? you can use umount /cfs-mountpoint

**Comment by mervinkid** [comment]
@netdata-be 

Thanks for your feedback.

The client will not automatically unmount after stopping the client. When umount the mount point manually, the client will automatically exit.
The purpose of this design is that once the client process is killed for some reason, the business system using storage will perceive an exception due to a write failure.
If the mount point is automatically unmounted, the business system that is using the storage will not be aware of it, and will continue to write data to the mount point, while actually writing data to the local disk.

You can umount the mointpoint and stop fuse client by following command:
```bash
$ fusermount -u ${YOUR_MOUNT_POINT}
```
