### ISSUE TITLE
CFS提供Java的API吗

### ISSUE THREAD

**Issue by BelieverDZG** [chubaofs/chubaofs#547]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mervinkid** [comment]
@BelieverDZG 

Currently only provide POSIX-compatible file system interface (via mountable **FUSE client**) and S3 compatible object storage interface (provided by **ObjectNode**).

We currently have no plans to provide APIs specific to certain development languages like HDFS. Because such APIs are less versatile and do not conform to POSIX semantics.

**Comment by hooklee2000** [comment]
I found cfsclient (https://github.com/chengyu-l/cfsclient)， it use grpc protocol to connect server.you can also use chubaofs client as local file system ,

**Comment by Victor1319** [comment]
@BelieverDZG do you want to use chubaofs by java sdk? it's already supported in latest version
